### ISSUE TITLE
New Beanie `Link` directive fails with mongomock harness

### ISSUE THREAD

**Issue by cypherlou** [michaelkryukov/mongomock_motor#5]
Hey Michael, I was referred to your library by the guys at `mongomock` who think my issue is probably with `mongomock-motor`. This [is the ticket](https://github.com/mongomock/mongomock/issues/759) I raised with them. Does this make any sense? Do you agree with them?

**Comment by cypherlou** [comment]
I've upgraded to the latest version (0.0.3) which seems to have fixed the issue. Sorry to hassle you.

**Comment by michaelkryukov** [comment]
Hey, the issue is actually valid, we don't mock attributes at the moment (but should). That's why Links don't work. Adding attributes is not that hard.

Also, I notice that the most recent version of beanie uses `command`, which is not supported by mongomock at all. That is separate issues that I will look into as soon as I can.

**Comment by michaelkryukov** [comment]
I implemented proper attributes and limited support for `command` in order to not fail beanie initialization in commit: https://github.com/michaelkryukov/mongomock_motor/commit/9ac7a759680ece96de01c1112e8d8fe0b236a526

But it looks like `Link` doesn't work fully because of `mongomock` implementation of aggregation pipeline stage `$lookup` don't work properly with `DBRef`.  I guess this is because `$lookup` was changed in mongo 5+, but `mongomock` still has implementation compatible with mongo 4+. I will post a comment on the issue in `mongomock`, but it looks like I can't do much from `mongomock-motor`.

**Comment by Itay4** [comment]
@michaelkryukov got any idea for a workaround (maybe with patching `mongomock`) or we have to wait for fix on their side?
